#!/bin/bash

# Function to send a notification
send_notification() {
    # Replace this with your favorite notification command
    notify-send "Volume Changed" "Volume was adjusted. ${1}"
    pactl list sinks \
      | grep -E '^Sink #4442' -A 15 \
      | grep -E '^\s+Volume:' \
      | sed -nr 's/.+\s([0-9]{1,3}%)\s.+/\1/p'
}

pactl subscribe | while read -r event; do
  if [[ $event =~ "sink" ]]; then
    send_notification "${event}"
  fi
done

