#!/usr/bin/env bash

monitor="${1:-}${1:+_}"

gib_workspace_names () {
  wmctrl -d \
    | awk '{ print $1 " " $2 " " $9 }' \
    | grep -v "NSP" \
    | grep "${monitor:-}"
}

gib_workspace_yuck() {
  buffered=""
  gib_workspace_names | while read -r id active name; do
    name="${name#*_}"
    if test "${active}" = '*'; then
      active_class="focused"
    else
      active_class="inactive"
    fi

    if wmctrl -l | grep --regexp '.*\s\+'"$id"'\s\+.*' >/dev/null; then
      button_class="occupied"
      #button_name="◆"
    else
      button_class="empty"
    fi
    button_name="${name}"
    buffered+="(button :class \"$button_class $active_class\"  :onclick \"wmctrl -s $id\" \"$button_name\")"
    if [ $button_class = "occupied" -o $active_class = "active" ]; then
      echo -n "$buffered"
      buffered=""
    fi
  done
}

xprop -spy -root _NET_CURRENT_DESKTOP | while read -r; do
  printf '%s\n' '(box :orientation "h" :class "workspaces" :space-evenly false :halign "center" :valign "center" :vexpand true '"$(gib_workspace_yuck)"')'
done
