# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5a309a06-9747-450e-83a4-817908095b01";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd:1" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/5a309a06-9747-450e-83a4-817908095b01";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd:1" "noatime"];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/5a309a06-9747-450e-83a4-817908095b01";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd:1" "noatime"];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/5a309a06-9747-450e-83a4-817908095b01";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" "compress=zstd:1" "noatime"];
    };

  fileSystems."/games" =
    { device = "/dev/disk/by-uuid/5a309a06-9747-450e-83a4-817908095b01";
      fsType = "btrfs";
      options = [ "subvol=@games" "compress=zstd:1" "noatime"];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/5a309a06-9747-450e-83a4-817908095b01";
      fsType = "btrfs";
      options = [ "subvol=@swap" "noatime"];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F0B2-2960";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
