#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o noclobber
#set -o nounset
#set -o xtrace

# Script utilities {{{
colours () { # {{{
  export RESET=$'\e[0;39m'

  export E_BOLD=$'\e[1m'
  export E_DIM=$'\e[2m'
  export E_UNDERLINE=$'\e[4m'
  export E_BLINK=$'\e[5m'
  export E_INVERT=$'\e[7m'
  export E_HIDDEN=$'\e[8m'

  export R_NORMAL=$'\e[0m'
  export R_BOLD=$'\e[21m'
  export R_DIM=$'\e[22m'
  export R_UNDERLINE=$'\e[24m'
  export R_BLINK=$'\e[25m'
  export R_INVERT=$'\e[27m'
  export R_HIDDEN=$'\e[28m'

  export C_DEFAULT=$'\e[19m'
  export C_BLACK=$'\e[30m'
  export C_RED=$'\e[31m'
  export C_GREEN=$'\e[32m'
  export C_YELLOW=$'\e[33m'
  export C_BLUE=$'\e[34m'
  export C_MAGENTA=$'\e[35m'
  export C_CYAN=$'\e[36m'
  export C_LGRAY=$'\e[37m'
  export C_DGRAY=$'\e[90m'
  export C_LRED=$'\e[91m'
  export C_LGREEN=$'\e[92m'
  export C_LYELLOW=$'\e[93m'
  export C_LBLUE=$'\e[94m'
  export C_LMAGENTA=$'\e[95m'
  export C_LCYAN=$'\e[96m'
  export C_WHITE=$'\e[97m'

  export B_DEFAULT=$'\e[49m'
  export B_BLACK=$'\e[40m'
  export B_RED=$'\e[41m'
  export B_GREEN=$'\e[42m'
  export B_YELLOW=$'\e[43m'
  export B_BLUE=$'\e[44m'
  export B_MAGENTA=$'\e[45m'
  export B_CYAN=$'\e[46m'
  export B_LGRAY=$'\e[47m'
  export B_DGRAY=$'\e[100m'
  export B_LRED=$'\e[101m'
  export B_LGREEN=$'\e[102m'
  export B_LYELLOW=$'\e[103m'
  export B_LBLUE=$'\e[104m'
  export B_LMAGENTA=$'\e[105m'
  export B_LCYAN=$'\e[106m'
  export B_WHITE=$'\e[106m'
} # }}}
colours

send () { # {{{
  local callback="${@:5:1}"
  (
  # $1: Type of message, e.g. ERROR
  # $2: Effects, e.g. ${green}
  # $3: Message
  # $4: Callback
  local err="${@:1:1}"
  local eff="${@:2:1}"
  local msg="${@:3:1}"
  local mff="${@:4:1}"
  test -z "${mff}" -o "${mff}" = "-" && local mff="${eff}"
  # Max length of word
  local len=5
  local pad=$(( ${len} - ${#err} ))

  printf "[ ${eff}${err}${RESET}%-${pad}s ] ${mff}${msg}${RESET}\n"
  )
  test -n "${callback}" && eval "${callback}"
} # }}}
# }}}

setup_ssh_key () { # {{{
  read -p "SSH key comment: " SSH_KEY_COMMENT
  ssh-keygen -f ~/.ssh/id_rsa -t rsa -b 4096 -o -a 100 -C "${SSH_KEY_COMMENT}"
  cat ~/.ssh/id_rsa.pub
  read -p "Please add this key to your git provider and press Enter when you're done"
} # }}}

setup_fonts () { # {{{
  FONTS_REPO="git@github.com:runarsf/fonts.git"
  git clone "${FONTS_REPO}" ~/.fonts
  sudo fc-cache -f
} # }}}

dotfiles_bare_repo () { # {{{
  DOT_REPO="git@github.com:runarsf/dotfiles.git"
  DOT_DIR="${HOME}/.config/dotfiles/.git"
  DOT_TREE="${HOME}"

  # Create parent directories of DOT_DIR
  mkdir -p "$(dirname "${DOT_DIR}")"

  # Clone repo
  git clone --bare "${DOT_REPO}" "${DOT_DIR}"

  # Set up temporary alias
  alias dotfiles='git --git-dir="${DOT_DIR}" --work-tree="${DOT_TREE}"'

  # Only show tracked files in version control
  dotfiles config --local status.showUntrackedFiles no

  # Checkout your dotfiles
  # NB! If this failed, you simply have to do as git tells you to. Either delete or move the conflicting files.
  # If you're on a new system you can most likely delete them without any issues.
  # Continue reading for more info.
  dotfiles checkout
} # }}}

install_packages () { # {{{
  distro="${1}"
  method="${2}"
  packages="${@:3}"
  if [[ "$(cat /etc/*-release | grep ID_LIKE)" = *"${distro}"* ]]; then
    case "${distro}-${method}" in
      arch-pacman)
        sudo pacman -Syu ${packages}
        ;;
      arch-yay)
        yay -Syu ${packages}
        ;;
      debian-apt)
        #send "INFO" "${C_LBLUE}" "Installing packages for ${distro} (${method})."
        DEBIAN_FRONTEND=noninteractive sudo apt-get update
        DEBIAN_FRONTEND=noninteractive sudo apt-get upgrade -y
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -y ${packages}
        ;;
    esac
  fi
} # }}}

desktop () { # {{{
  install_packages arch pacman git alacritty bspwm sxhkd rofi base-devel dunst vim neovim polybar nitrogen tmux picom yay ueberzug mediainfo trash-cli highlight dnsutils # ffmpegthumbnailer poppler odt2txt docx2txt
  install_packages arch yay wmutils-git dragon-drag-and-drop gllock-git ttf-font-awesome-4 lf glow # undistract-me-git
  install_packages debian apt alacritty
  install_fonts
} # }}}

case "${1}" in
  desktop) desktop; shift;;
  test) eval "${2}"; shift;shift;;
  *) printf "Unrecognized action: ${1}\n"
esac
