#!/usr/bin/env bash

eww update volpoll=false
#mkdir -p pipes
#mkfifo pipes/volume

handle_sink_event() {
    sink="$(printf '%s\n' "${1}" | sed -nr 's/.+\s(#[0-9]+)$/\1/p')"
    volume="$(pactl list sinks \
      | grep -E "^Sink ${sink}" -A 15 \
      | grep -E '^\s+Volume:' \
      | sed -nr 's/.+\s([0-9]{1,3}%)\s.+/\1/p')"
}

# pactl subscribe | while read -r event; do
#   if [[ "${event}" =~ "sink" ]]; then
#     handle_sink_event "${event}"
#   fi
# done
# 
# cleanup() {
#   #rm -f pipes/volume
#   eww close volume
# }
# 
# trap cleanup EXIT
