#!/usr/bin/env bash
set -o errexit

# https://forums.linuxmint.com/viewtopic.php?t=187819
# dconf list /org/

action="${1}"

if ! command -v "dconf" >/dev/null 2>&1; then
  printf "Command 'dconf' not found."
  exit 1
fi

case "${action}" in
  dump)
    dconf dump /org/cinnamon/ > "${HOME}"/.config/dotfiles/cinnamon/cinnamon.dconf
    dconf dump /org/nemo/ > "${HOME}"/.config/dotfiles/cinnamon/nemo.dconf
    dconf dump /org/gtk/ > "${HOME}"/.config/dotfiles/cinnamon/gtk.dconf
    dconf dump /org/gnome/ > "${HOME}"/.config/dotfiles/cinnamon/gnome.dconf
    printf "Configs dumped to ${HOME}/.config/dotfiles/cinnamon"
    exit 0;;
  load)
    dconf load /org/cinnamon/ < "${HOME}"/.config/dotfiles/cinnamon/cinnamon.dconf
    dconf load /org/nemo/ < "${HOME}"/.config/dotfiles/cinnamon/nemo.dconf
    dconf load /org/gtk/ < "${HOME}"/.config/dotfiles/cinnamon/gtk.dconf
    dconf load /org/gnome/ < "${HOME}"/.config/dotfiles/cinnamon/gnome.dconf
    printf "Configs loaded from ${HOME}/.config/dotfiles/cinnamon"
    exit 0;;
  reset)
    dconf reset -f /org/cinnamon/
    dconf reset -f /org/nemo/
    dconf reset -f /org/gtk/
    dconf reset -f /org/gnome/
    printf "Configs reset"
    exit 0;;
  *)
    printf "Unrecognized action, valid actions are: dump, load, reset"
    exit 1;;
esac
