#!/usr/bin/env bash

if command -v "gist" >/dev/null 2>&1; then
  gist="gist"
elif command -v "gist-paste" >/dev/null 2>&1; then
  gist="gist-paste"
else
  printf "'gist' not installed...\n"
  exit 0
fi

"${gist}" -r 6368e52a91c51d1e106c1fa38009f46e > ~/.local/bin/jot
chmod +x ~/.local/bin/jot
