local wezterm = require 'wezterm';

return {
  font = wezterm.font_with_fallback({
    "JetBrains Mono",
    "Operator Mono",
  }),
  color_scheme = "Batman",

  -- https://wezfurlong.org/wezterm/config/keys.html#default-shortcut--key-binding-assignments
  disable_default_key_bindings = true,
  leader = { key="a", mods="CTRL", timeout_milliseconds=1000 },
  keys = {
    {key="t",          mods="CTRL",           action=wezterm.action{SpawnTab="CurrentPaneDomain"}},
    {key="t",          mods="CTRL|SHIFT",     action=wezterm.action{SpawnTab="DefaultDomain"}},
    {key="w",          mods="CTRL",           action=wezterm.action{CloseCurrentTab={confirm=true}}},
    {key="c",          mods="ALT",            action=wezterm.action{CopyTo="Clipboard"}},
    {key="v",          mods="ALT",            action=wezterm.action{PasteFrom="Clipboard"}},
    {key="c",          mods="CTRL|SHIFT",     action=wezterm.action{CopyTo="Clipboard"}},
    {key="v",          mods="CTRL|SHIFT",     action=wezterm.action{PasteFrom="Clipboard"}},
    {key="Enter",      mods="ALT",            action="ToggleFullScreen"},
    {key="+",          mods="CTRL",           action="IncreaseFontSize"},
    {key="-",          mods="CTRL",           action="DecreaseFontSize"},
    {key="=",          mods="CTRL",           action="ResetFontSize"},
    {key="t",          mods="ALT",            action="ShowTabNavigator"},
    {key="1",          mods="CTRL|ALT",       action=wezterm.action{ActivateTab=0}},
    {key="2",          mods="CTRL|ALT",       action=wezterm.action{ActivateTab=1}},
    {key="3",          mods="CTRL|ALT",       action=wezterm.action{ActivateTab=2}},
    {key="4",          mods="CTRL|ALT",       action=wezterm.action{ActivateTab=3}},
    {key="5",          mods="CTRL|ALT",       action=wezterm.action{ActivateTab=4}},
    {key="6",          mods="CTRL|ALT",       action=wezterm.action{ActivateTab=5}},
    {key="7",          mods="CTRL|ALT",       action=wezterm.action{ActivateTab=6}},
    {key="8",          mods="CTRL|ALT",       action=wezterm.action{ActivateTab=7}},
    {key="9",          mods="CTRL|ALT",       action=wezterm.action{ActivateTab=-1}},
    {key="Tab",        mods="CTRL",           action=wezterm.action{ActivateTabRelative=1}},
    {key="Tab",        mods="CTRL|SHIFT",     action=wezterm.action{ActivateTabRelative=-1}},
    {key="PageUp",     mods="SHIFT",          action=wezterm.action{ScrollByPage=-1}},
    {key="PageDown",   mods="SHIFT",          action=wezterm.action{ScrollByPage=1}},
    {key="r",          mods="CTRL|SHIFT|ALT", action="ReloadConfiguration"},
    {key="l",          mods="CTRL|SHIFT|ALT", action="ShowDebugOverlay"},
    {key="f",          mods="CTRL|SHIFT",     action=wezterm.action{Search={CaseInSensitiveString=""}}},
    {key="-",          mods="LEADER",         action=wezterm.action{SplitVertical={domain="CurrentPaneDomain"}}},
    {key="|",          mods="LEADER",         action=wezterm.action{SplitHorizontal={domain="CurrentPaneDomain"}}},
    {key="LeftArrow",  mods="ALT|SHIFT",      action=wezterm.action{AdjustPaneSize={"Left", 5}}},
    {key="RightArrow", mods="ALT|SHIFT",      action=wezterm.action{AdjustPaneSize={"Right", 5}}},
    {key="UpArrow",    mods="ALT|SHIFT",      action=wezterm.action{AdjustPaneSize={"Up", 5}}},
    {key="DownArrow",  mods="ALT|SHIFT",      action=wezterm.action{AdjustPaneSize={"Down", 5}}},
    {key="LeftArrow",  mods="ALT",            action=wezterm.action{ActivatePaneDirection="Left"}},
    {key="RightArrow", mods="ALT",            action=wezterm.action{ActivatePaneDirection="Right"}},
    {key="UpArrow",    mods="ALT",            action=wezterm.action{ActivatePaneDirection="Up"}},
    {key="DownArrow",  mods="ALT",            action=wezterm.action{ActivatePaneDirection="Down"}},
  },
}
