local wezterm = require 'wezterm';

return {
  font = wezterm.font_with_fallback({
    "JetBrainsMono NF",
    "Operator Mono",
  }),
  freetype_load_target = "Light",
  freetype_render_target = "HorizontalLcd",
  -- front_end = "OpenGL",
  color_scheme = "ayu",
  window_padding = {
    left   = 0,
    right  = 0,
    top    = 0,
    bottom = 0,
  },
  hide_tab_bar_if_only_one_tab = true,
  quick_select_patterns = {
    "[0-9a-f]{7,40}",
  },
  exit_behavior = "CloseOnCleanExit",
  clean_exit_codes = { 130 },
  skip_close_confirmation_for_processes_named = { "wezterm" },
  enable_scroll_bar = false,
  unix_domains = {
    { name = "unix" },
    { name = "scratch" },
  },
  -- default_gui_startup_args = {"connect", "unix"},

  -- https://wezfurlong.org/wezterm/config/keys.html#default-shortcut--key-binding-assignments
  disable_default_key_bindings = true,
  leader = { key="a", mods="CTRL", timeout_milliseconds=2000 },
  keys = {
    {key="n",          mods="LEADER",         action=wezterm.action{SpawnTab="CurrentPaneDomain"}},
    {key="t",          mods="LEADER|SHIFT",   action=wezterm.action{SpawnTab="CurrentPaneDomain"}},
    {key="w",          mods="CTRL",           action=wezterm.action{CloseCurrentTab={confirm=true}}},
    {key="c",          mods="ALT",            action=wezterm.action{CopyTo="Clipboard"}},
    {key="v",          mods="ALT",            action=wezterm.action{PasteFrom="Clipboard"}},
    {key="c",          mods="CTRL|SHIFT",     action=wezterm.action{CopyTo="Clipboard"}},
    {key="v",          mods="CTRL|SHIFT",     action=wezterm.action{PasteFrom="Clipboard"}},
    {key="Enter",      mods="ALT",            action="ToggleFullScreen"},
    {key="+",          mods="CTRL",           action="IncreaseFontSize"},
    {key="-",          mods="CTRL",           action="DecreaseFontSize"},
    {key="=",          mods="CTRL",           action="ResetFontSize"},
    {key="t",          mods="ALT",            action="ShowTabNavigator"},
    {key="x",          mods="LEADER|SHIFT",   action="ActivateCopyMode"},
    {key="r",          mods="LEADER",         action="ReloadConfiguration"},
    {key=" ",          mods="LEADER",         action="QuickSelect"},
    {key="1",          mods="LEADER",         action=wezterm.action{ActivateTab=0}},
    {key="2",          mods="LEADER",         action=wezterm.action{ActivateTab=1}},
    {key="3",          mods="LEADER",         action=wezterm.action{ActivateTab=2}},
    {key="4",          mods="LEADER",         action=wezterm.action{ActivateTab=3}},
    {key="5",          mods="LEADER",         action=wezterm.action{ActivateTab=4}},
    {key="6",          mods="LEADER",         action=wezterm.action{ActivateTab=5}},
    {key="7",          mods="LEADER",         action=wezterm.action{ActivateTab=6}},
    {key="8",          mods="LEADER",         action=wezterm.action{ActivateTab=7}},
    {key="9",          mods="LEADER",         action=wezterm.action{ActivateTab=-1}},
    {key="h",          mods="CTRL|SHIFT",     action=wezterm.action{ActivateTabRelative=1}},
    {key="l",          mods="CTRL|SHIFT",     action=wezterm.action{ActivateTabRelative=-1}},
    {key="Tab",        mods="CTRL",           action=wezterm.action{ActivateTabRelative=1}},
    {key="Tab",        mods="CTRL|SHIFT",     action=wezterm.action{ActivateTabRelative=-1}},
    {key="PageUp",     mods="SHIFT",          action=wezterm.action{ScrollByPage=-1}},
    {key="PageDown",   mods="SHIFT",          action=wezterm.action{ScrollByPage=1}},
    {key="r",          mods="CTRL|SHIFT|ALT", action="ReloadConfiguration"},
    {key="l",          mods="CTRL|SHIFT|ALT", action="ShowDebugOverlay"},
    {key="l",          mods="CTRL|ALT",       action=wezterm.action{ClearScrollback="ScrollbackAndViewport"}},
    {key="f",          mods="CTRL|SHIFT",     action=wezterm.action{Search={CaseInSensitiveString=""}}},
    {key="-",          mods="LEADER",         action=wezterm.action{SplitVertical={domain="CurrentPaneDomain"}}},
    {key="|",          mods="LEADER",         action=wezterm.action{SplitHorizontal={domain="CurrentPaneDomain"}}},
    {key="LeftArrow",  mods="ALT|CTRL",       action=wezterm.action{AdjustPaneSize={"Left", 5}}},
    {key="RightArrow", mods="ALT|CTRL",       action=wezterm.action{AdjustPaneSize={"Right", 5}}},
    {key="UpArrow",    mods="ALT|CTRL",       action=wezterm.action{AdjustPaneSize={"Up", 5}}},
    {key="DownArrow",  mods="ALT|CTRL",       action=wezterm.action{AdjustPaneSize={"Down", 5}}},
    {key="LeftArrow",  mods="SHIFT",          action=wezterm.action{ActivatePaneDirection="Left"}},
    {key="RightArrow", mods="SHIFT",          action=wezterm.action{ActivatePaneDirection="Right"}},
    {key="UpArrow",    mods="SHIFT",          action=wezterm.action{ActivatePaneDirection="Up"}},
    {key="DownArrow",  mods="SHIFT",          action=wezterm.action{ActivatePaneDirection="Down"}},
    {key="z",          mods="LEADER",         action="TogglePaneZoomState"},
    {key="q",          mods="LEADER",         action=wezterm.action{CloseCurrentPane={confirm=true}}},
    {key="d",          mods="LEADER",         action=wezterm.action{DetachDomain="CurrentPaneDomain"}},
  },
}
