#!/usr/bin/env bash

action=${1}
arg=${2}

function usage {
  echo "  $(basename ${0})"
  echo "    Sort columns based on tags."
  echo ""
  exit
}

test "${action}" = "usage" && usage

cd "${TODO_DIR}"

# TODO: Sort with fzf (prj / ctx / all)

# > Get all tasks containing +
# > Remove the last two lines
# > Remove color codes
# > Get *only* all words starting with +
# > Sort
# > Remove duplicate words
if test "${arg}" = "prj" -o -z "${arg}"; then
  projects=$(${TODO_SH} ls "+" \
           | head -n -2 \
           | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" \
           | \grep --color=never -oE '\+\S+' \
           | sort \
           | uniq)

  for proj in ${projects}; do
    printf "${proj}\n"
    seq -s= $((${#proj}+1)) | tr -d '[:digit:]' # '=' * proj + 1
    ${TODO_SH} ls "${proj}" | head -n -2
    printf "\n"
  done
fi

if test "${arg}" = "ctx" -o -z "${arg}"; then
  contexts=$(${TODO_SH} ls "@" \
           | head -n -2 \
           | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" \
           | \grep --color=never -oE '\@\S+' \
           | sort \
           | uniq)

  for ctx in ${contexts}; do
    printf "${ctx}\n"
    seq -s= $((${#ctx}+1)) | tr -d '[:digit:]' # '=' * proj + 1
    ${TODO_SH} ls "${ctx}" | head -n -2
    printf "\n"
  done
fi

if test -z "${arg}"; then
  uncategorized="$(${TODO_SH} ls -"+" | head -n -2)"
  if test -n "${uncategorized}"; then
    printf "Uncategorized\n=============\n"
    printf "${uncategorized}"
  fi
fi

#printf ${projects} | grep -w -v -e "+wifi" -e "+unifi"
