#!/usr/bin/env bash

action=${1}
shift
mode=${1}

function usage {
  echo "  $(basename ${0}) [-v]"
  echo "    Record all changes in Git repository located at $TODO_DIR."
  echo "    If -v argument is provided, only a preview will be shown."
  echo ""
  exit
}

test "${action}" = "usage" && usage

${TODO_FULL_SH} archive

cd "${TODO_DIR}"
git diff
if test "${mode}" != "-v"; then
  git commit -a ${mode} -m "$(hostname): $(date +"%Y-%m-%d %H:%M:%S")"
fi

