#!/bin/bash

test "$1" = "usage" && exit 0

item="${2}"

# Take into account "del #ITEM TERM"
if test -z "${3}"; then
  getTodo "${item}"
fi

"${TODO_SH}" command "${@}"

test "${?}" -eq "0" \
  && test -z "${3}" \
  && "${TODO_SH}" note __rmfromtext "DDDD${todo}"
