#!/usr/bin/env bash

action=${1}

function usage {
	echo "  $(basename ${0})"
	echo "    Get git diff from ${TODO_DIR}."
	echo ""
	exit
}

test "${action}" = "usage" && usage

cd "${TODO_DIR}"

git status
git diff
