#!/usr/bin/env bash

action=$1

function usage {
	echo "  $(basename $0)"
	echo "    Pull changes into git repository located at $TODO_DIR."
	echo "    Always pulls from origin/master into local master branch."
	echo ""
	exit
}

[ "$action" = "usage" ] && usage

cd "$TODO_DIR"

branch_name="$(git symbolic-ref HEAD 2>/dev/null)" ||
branch_name="(unnamed branch)"     # detached HEAD
branch_name=${branch_name##refs/heads/}

git fetch origin
git merge origin/${branch_name}

