#!/usr/bin/env bash

action=$1

function usage {
	echo "  $(basename $0)"
	echo "    Pushes all changes at $TODO_DIR to a remote repository."
	echo ""
	exit
}

[ "$action" = "usage" ] && usage

cd "$TODO_DIR"

branch_name="$(git symbolic-ref HEAD 2>/dev/null)" ||
branch_name="(unnamed branch)"     # detached HEAD
branch_name=${branch_name##refs/heads/}

git push -u origin ${branch_name}

