#!/bin/sh

printf '%s\n' "Running post-merge hook."

export GPG_TTY="$(tty)"

source "$(git --exec-path)/git-sh-setup"

set -o errexit
set -o nounset

GIT_DIR="$(git rev-parse --git-dir)"
GIT_WORKING_TREE="$(git rev-parse --show-toplevel)"

while IFS= read -r dotfile; do
  encfile="$(realpath --no-symlinks "${GIT_WORKING_TREE}/${dotfile}")"
  decfile="$(printf '%s\n' "${encfile}" | sed -e 's/.enc$//')"
  if test ! -f "${decfile}"; then
    printf '%s\n' "Decrypting ${encfile} -> ${decfile}"
    gpg --output "${decfile}" --decrypt "${encfile}"
  fi
done < <(git --git-dir="${GIT_DIR}" ls-tree --full-tree -r 'HEAD' --name-only | grep '\.enc$')
