#!/bin/sh

printf '%s\n' "Running pre-commit hook."

export GPG_TTY="$(tty)"

source "$(git --exec-path)/git-sh-setup"

set -o errexit
set -o nounset

GIT_DIR="$(git rev-parse --git-dir)"
GIT_WORKING_TREE="$(git rev-parse --show-toplevel)"

GPG_USER="root@runarsf.dev"

while IFS= read -r dotfile; do
  encfile="$(realpath --no-symlinks "${GIT_WORKING_TREE}/${dotfile}")"
  decfile="$(printf '%s\n' "${encfile}" | sed -e 's/.enc$//')"
  if test -f "${decfile}"; then
    printf '%s\n' "Encrypting ${decfile} -> ${encfile}"
    rm -f "${encfile}"
    gpg --output "${encfile}" --encrypt --recipient "${GPG_USER}" "${decfile}"
    git --git-dir="${GIT_DIR}" --work-tree="${GIT_WORKING_TREE}" add "${encfile}"
  fi
done < <(git --git-dir="${GIT_DIR}" --work-tree="${GIT_WORKING_TREE}" ls-files --full-name --deduplicate --no-empty-directory "${GIT_WORKING_TREE}" | grep '\.enc$')
