#!/bin/sh

exec stack ghc --  \
  --make xmonad.hs \
  -i               \
  -ilib            \
  -fforce-recomp   \
  -main-is main    \
  -v0              \
  -o "${1}"

DISPLAY=:0 notify-send "XMonad" "XMonad recompiled successfully!"
