hooks:
  cat: [ "cat", "${file}" ]
  chmod: [ "chmod", "+x", "${file}" ]

groups:
  rofi:
    path: ~/.config/rofi
    hooks: chmod
    files:
      - url: https://raw.githubusercontent.com/mattydebie/bitwarden-rofi/master/bwmenu
        path: bwmenu
      - url: https://raw.githubusercontent.com/davatorium/rofi-scripts/master/tmux_session.sh
        path: rofi-tmux

