# https://github.com/runarsf/dotfiles/blob/master/.local/bin/succ
# TODO Download entire folders from github
# TODO Path should have WINDOWS_PATH, LINUX_PATH, etc.

hooks:
    none: [ "echo" ]
    info: [ "echo", "-e", "\n - File: ${__file}\n - Path: ${__path}" ]
    cat: [ "cat", "${__file}" ]
    chmod: [ "chmod", "+x", "${__file}" ]
    mkdir: [ "mkdir", "-p", "${__path}" ]
    rm: [ "rm", "-f", "${__file}" ]
    rmdir: [ "rm", "-rf", "${__path}" ]
    pip: [ "python3", "-m", "pip", "--no-input", "install", "-r", "${__file}" ]

settings:
  default_group: None
  show_hook_content: false

collections:
  dotfiles:
    - succ
    - bspwm
    - rofi
  windows:
    - windows_bin
    - windows_configs

# $1 can be a collection or a group, where collection takes precedence.
# If you want to use a group over a collection, use -g|--group <group>.
# Providing a name isn't required, but will save a request to the page.

groups:
  succ:
    path: ~/.local/bin
    pre_hook: mkdir
    hooks: chmod
    strategy: overwrite
    files:
      - url: https://raw.githubusercontent.com/runarsf/dotfiles/master/.local/bin/succ
        path: succ
      - url: https://raw.githubusercontent.com/runarsf/dotfiles/master/.config/.succ.yml
        path: ~/.config/.succ.yml
  bspwm: # Remember to add "${XDG_CONFIG_HOME:-${HOME}/.config}/bspwm/scripts" to PATH in .profile
    pre_hooks: mkdir
    hooks: [ info, chmod ]
    strategy: skip # overwrite/yes, skip/no, ask
    path: ~/.config/bspwm/scripts
    files:
      - https://raw.githubusercontent.com/runarsf/dotfiles/master/.config/bspwm/scripts/bspwm_double_borders
      - https://raw.githubusercontent.com/runarsf/dotfiles/master/.config/bspwm/scripts/bspwm_focus
      - https://raw.githubusercontent.com/runarsf/dotfiles/master/.config/bspwm/scripts/bspwm_gaming
      - https://raw.githubusercontent.com/runarsf/dotfiles/master/.config/bspwm/scripts/bspwm_monitors
      - https://raw.githubusercontent.com/runarsf/dotfiles/master/.config/bspwm/scripts/bspwm_move
      - https://raw.githubusercontent.com/runarsf/dotfiles/master/.config/bspwm/scripts/bspwm_resize
      - https://raw.githubusercontent.com/runarsf/dotfiles/master/.config/bspwm/scripts/bspwm_rofi_layouts
      - https://raw.githubusercontent.com/runarsf/dotfiles/master/.config/bspwm/scripts/bspwm_rofi_layouts
      - https://raw.githubusercontent.com/runarsf/dotfiles/master/.config/bspwm/scripts/bspwm_scratchpad
      - https://raw.githubusercontent.com/runarsf/dotfiles/master/.config/bspwm/scripts/bspwm_windowgrabber
      - https://raw.githubusercontent.com/runarsf/dotfiles/master/.config/bspwm/scripts/bspwm_zoom
      - https://raw.githubusercontent.com/runarsf/dotfiles/master/.config/bspwm/scripts/cleanfullscreen
      - https://raw.githubusercontent.com/runarsf/dotfiles/master/.config/bspwm/scripts/prompt
      - https://raw.githubusercontent.com/runarsf/dotfiles/master/.config/bspwm/scripts/single_node_border
      - https://raw.githubusercontent.com/runarsf/dotfiles/master/.config/bspwm/scripts/toggleprogram
      - url: https://raw.githubusercontent.com/runarsf/dotfiles/master/.local/bin/toggleprogram
        path: ~/.local/bin/toggleprogram
      - url: https://raw.githubusercontent.com/runarsf/dotfiles/master/.local/bin/prompt
        path: ~/.local/ibn/prompt
  rofi:
    path: ~/.config/rofi
    hooks: chmod
    strategy: skip # overwrite/yes, skip/no, ask
    pre_hooks: mkdir
    files:
      - url: https://raw.githubusercontent.com/mattydebie/bitwarden-rofi/master/bwmenu
        path: bwmenu
      - url: https://raw.githubusercontent.com/davatorium/rofi-scripts/master/tmux_session.sh
        path: rofi-tmux
      - url: https://raw.githubusercontent.com/M3NIX/rofi-spotify/master/requirements.txt
        path: requirements.txt
        hooks: pip
      - url: https://raw.githubusercontent.com/M3NIX/rofi-spotify/master/rofi-spotify.py
        path: rofi-spotify
  windows_bin:
    path: ~/bin
    pre_hook: mkdir
    hooks: chmod
    strategy: overwrite
    files:
      - url: https://raw.githubusercontent.com/runarsf/dotfiles/master/.local/bin/succ
        path: succ
      - url: https://raw.githubusercontent.com/runarsf/dotfiles/master/.config/.succ.yml
        path: ~/.config/.succ.yml
  windows_configs:
    path: ~/.config
    pre_hooks: mkdir
    strategy: overwrite
    files:
      - url: https://raw.githubusercontent.com/runarsf/dotfiles/master/.config/nvim/init.vim
        path: ~/.config/nvim/init.vim
      - url: https://raw.githubusercontent.com/runarsf/dotfiles/master/.config/zsh/.zshrc
        path: ~/.zshrc
        pre_hooks: []
      - url: https://raw.githubusercontent.com/runarsf/dotfiles/master/.config/starship.toml
        path: ~/.config/starship.toml
