# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

[character]
success_symbol = "[»](green)"
error_symbol = "[»](red)"

[hostname]
disabled = true
ssh_only = true

[cmd_duration]
min_time = 10000
show_milliseconds = false
format = "[$duration]($style) "

[nodejs]
format = "[$symbol$version]($style) "

[battery]
disabled = true

[directory]
truncation_length = 2

[username]
disabled = true

[package]
disabled = true

[git_branch]
format = "[$symbol$branch]($style) "
