#!/usr/bin/env bash
# vim: set foldmethod=marker foldlevel=0 nomodeline:
bspc rule -r "*"

mainmonitor="$(bspc query --monitors --names | grep -v LVDS | head -n 1)"
if ! echo "$mainmonitor" | grep LVDS >/dev/null 2>&1; then
  xrandr --output "$mainmonitor" --auto --output LVDS1 --off
fi

bspc monitor $mainmonitor -d 1 2 3 4 5 6 7 8 9 0
bspc desktop -f 1

#bspc config split_ratio 0.52
#bspc config borderless_monocle true
#bspc config gapless_monocle true
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resuze_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color "#4c566a"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"

#bspc config top_padding 24
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 3
bspc config window_gap 15

# https://www.reddit.com/r/bspwm/comments/85hr4c/making_a_scratchpaddropdown_terminal_in_bspwm/
#dropdownname="dropdown"
#bspc query -N -n .hidden >/dev/null || setsid $TERMINAL -n "$dropdownname" -e dropdown >/dev/null 2>&1 &
#bspc rule -a St:$dropdownname hidden=on
#bspc rule -a St:$dropdownname sticky=on
#bspc rule -a St:$dropdownname state=floating

#bspc config external_rules_command "$(which floaters)"

# Rules {{{
# FIXME: Double check these classes
# TODO: Create function to automatically apply rules from array
bspc rule -a discord desktop=^2
bspc rule -a Mattermost desktop=^2
bspc rule -a slack desktop=^2
bspc rule -a Steam desktop=^5
bspc rule -a Screenkey manage=off
bspc rule -a Pavucontrol floating=on
bspc rule -a mpv floating=on
:'
declare -a rule_floating=(
  Pavucontrol
  mpv
)
declare -a rule_desktop_two=(
  discord
  Mattermost
  slack
)
declare -a rule_desktop_five=(
  Steam
)
declare -a rule_nomanage=(
  Screenkey
)

add_rules () {
  local rule="${1}"
  shift
  local classes=("${@}")
  for class in "${classes[@]}"; do
    bspc rule -a "${class}" "${rule}"
  done
}
add_rules "floating=on" "${rule_floating[@]}"
add_rules "desktop=^5" "${rule_desktop_two[@]}"
'
# }}}

exec_once () { # {{{
  # Note: Most programs are started in .xprofile
  cmd="${1}" # $1: command to run
  pid="${2:-${cmd%% *}}" # $2: what to check the pid of, defaults to first word of $1
  if ! pidof "${pid}"; then
    eval "${cmd} &"
  fi
  # if test -z "${BSPWM_STARTED}"; then
  # export BSPWM_STARTED=true
}

exec_once "discord"
# }}}
