#!/bin/bash

#notify-send "$*"

title="$(xtitle ${1})"
if [[ "${title}" =~ " - YouTube - " ]]; then
  bspc config -n "${1}" bottom_padding -12
  echo "border=off"
fi

#on=14 off=0
#bspc query -N -n .floating.window | xargs -I {node} bspc config -n {node} border_width "$on"
#bspc query -N -n .!floating.window | xargs -I {node} bspc config -n {node} border_width "$off"
#while read -r _ _ _ node state status; do
#    [[ "$state" == "floating" ]] && bspc config -n "$node" border_width "${!status}"
#done < <(bspc subscribe node_state)
