#!/usr/bin/env bash

test "${#}" -ne "3" && { echo "Needs exactly three arguments."; exit 1; }

motion="${1}"
direction="${2}"
size="${3}"

if test "${motion}" = "expand"; then
  # These expand the window's given side
  case "${direction}" in
    north) bspc node --resize top 0 -"${size}";;
    south) bspc node --resize bottom 0 "${size}";;
    west) bspc node --resize left -"${size}" 0;;
    east) bspc node --resize right "${size}" 0;;
  esac
else
  # These contract the window's given side
  case "$direction" in
    north) bspc node --resize top 0 "${size}";;
    south) bspc node --resize bottom 0 -"${size}";;
    west) bspc node --resize left "${size}" 0;;
    east) bspc node --resize right -"${size}" 0;;
  esac
fi
