#!/bin/sh
# Inpiration taken from https://github.com/neeasade/dotfiles/blob/master/wm/.wm/scripts/visual/2bspwm
# Depends on wmutils/opt:
#   sudo pacman -S base-devel
#   yay -S wmutils-git
# NB! Remember to set default settings in bspwmrc

# Default borders {{{
readonly default_border_width="$(bspc config border_width)"
readonly default_normal_border_color="$(bspc config normal_border_color | sed 's/^#//g')"
readonly default_focused_border_color="$(bspc config focused_border_color | sed 's/^#//g')"
# readonly default_active_border_color="$(bspc config active_border_color)"
# readonly default_urgent_border_color="$(bspc config urgent_border_color)"
restore () {
  bspc config border_width "${default_border_width}"
  bspc config normal_border_color   "#${default_normal_border_color}"
  bspc config focused_border_color  "#${default_focused_border_color}"
  # bspc config active_border_color   "${default_active_border_color}"
  # bspc config urgent_border_color   "${default_urgent_border_color}"
  # notify-send "$(basename "${0}")" "borders restored"
}
trap restore EXIT
# }}}

# PRESET: Default behaviour {{{
border_width_in_normal="$((default_border_width))"
border_color_in_normal="1E2030"

border_width_out_normal="$((border_width_in_normal + 2))"
border_color_out_normal="${default_normal_border_color}"

border_width_in_focused="${border_width_in_normal}"
border_color_in_focused="3C405C"

border_width_out_focused="${border_width_out_normal}"
border_color_out_focused="${border_color_out_normal}"

bspc config normal_border_color "#${border_color_out_normal}"
# }}}

# PRESET: Only focused node has double borders {{{
# border_width_in_normal="$((default_border_width * 2))"
# border_color_in_normal="${default_normal_border_color}"

# border_width_out_normal="${default_border_width}"
# border_color_out_normal="${default_focused_border_color}"

# border_width_in_focused="${border_width_out_normal}"
# border_color_in_focused="${border_color_out_normal}"

# border_width_out_focused="${border_width_in_normal}"
# border_color_out_focused="${border_color_in_normal}"

# bspc config normal_border_color "#${border_color_in_normal}"
# }}}

readonly width_normal="$((border_width_in_normal + border_width_out_normal))"
readonly width_focused="$((border_width_in_focused + border_width_out_focused))"

bspc config border_width "${width_normal}"
bspc config active_border_color "#${border_color_in_normal}"
bspc config focused_border_color "#${border_color_in_normal}"

bspwindows () {
  kind="${1:-active}"
  test "${#}" -gt "0" && shift

  case "${kind}" in
    active)
      bspc query -N -n ".local.descendant_of.window.leaf.!fullscreen.!hidden${*}";;
    inactive)
      bspc query -N -n ".local.!descendant_of.window.leaf.!fullscreen.!hidden${*}";;
    visible)
      bspc query -N -n ".local.!descendant_of.window.leaf.!fullscreen.!hidden${*}"
      bspc query -N -n ".local.descendant_of.window.leaf.!fullscreen.!hidden${*}";;
  esac
}

_chwb2() {
  colorType="${1}"
  shift

  _getVal() {
    eval echo \$${1}_${colorType}
  }

  test "${width_normal}" = "${width_focused}" \
  || echo "${@}" | sed 's/ /\n/g' | xargs -I{} bspc config -n {} border_width "$(_getVal width)"

  # -O '0xff123456' \
  # chwb2 -I 292b34 -O 30333d -i 3 -o 7 0xffA00001 2>/dev/null
  chwb2 \
    -I "$(_getVal border_color_in)" \
    -O "$(_getVal border_color_out)" \
    -i "$(_getVal border_width_in)" \
    -o "$(_getVal border_width_out)" "${@}" 2>/dev/null
}

_chwb2 focused "$(bspwindows)"
_chwb2 normal "$(bspwindows inactive)"

bspc subscribe node_state node_geometry node_focus | \
  while read msg; do
    _chwb2 focused $(bspwindows)
    _chwb2 normal $(bspwindows inactive)
  done
